### ISSUE TITLE
Collect feedback about SDK

### ISSUE THREAD

**Issue by shumkov** [dashpay/platform#2281]
We want to collect your feedback on using RS SDK / DPP in one place for our upcoming work to improve user experience. Please share your feelings, pain points, places you like, “nice to have” things, and other suggestions. Thank you!

**Comment by shumkov** [comment]
From @HashEngineering 

> Some things were or are missing from rs-sdk:
> - Replace document
> - Delete document
> - Core endpoints such as get_transaction
> - get status endpoint

> The API is simple with a common interface for all queries and for submitting state transitions (though the client doesn't need to consider state transitions but instead identities, documents, data contracts and votes)
> the `fetch` and `fetch_many` methods work quite well and have `_with_settings` variants to allow the client to specify their own request_settings for different retry parameters.
> The `Put*` interfaces are missing some things.  In my system, I prefer a `put_to_platform` and a `wait_for_result` method rather than a single method that does both.  The reason for this is that I want to `wait` on several different EvoNodes to return the state transition result.  I found this to ensure that the state transition was propogated during the username creation process which requires putting an identity, then two documents and in some cases, retrieving the vote information on contested domain documents.
> Even for `put_to_platform` , I have some extra retry that I have added to handle the cases of bad nodes.  Previously on testnet, I encountered EvoNodes that said the dpns contract did not exist.  In such cases, I would need to try again with a different EvoNode.  The ban features in the Sdk are hidden, so the client cannot ban such nodes.  Perhaps this could also be resolved with other checks in the SDK or dapi-cleint to retry.  Not sure if this happens anymore; it was first discovered with Platform 1.1 or 1.0 on testnet -- it may not happen anymore.

**Comment by shumkov** [comment]
From @QuantumExplorer 

> Generics for `fetch` and `fetch_many` are a bit tricky because you don't know what to pass, and you don't have autocomplete for this.

**Comment by shumkov** [comment]
@lklimek :

> On my side, the data model (aka `dpp` needs some review / tidying up. Of course these are strongly opinionated, I'm open to your opinions. Examples:
> There should be only one type for various stuff, for example `ExtendedEpochInfo` should be renamed to `EpochInfo`. Same applies to other types, like Document/ExtendedDocument, Contender/ContenderWithSerializedDocument, ...  - we should only have one type, others should be hidden unless someone uses some low-level crate / separate feature.
> Types should be self-contained, I mean - to put a Document, you should only provide the Document. Of course there must be some way to mark dependencies between Document, document type and DataContract - not sure how, but current approach is hard to use.
> implement serde (as per API guidelines) and then derive our encoding from it if possible
> documentation of DPP
> 2. In terms of DAPI, we should also have REST responding with JSON for proof-less mode; that will make debugging much easier.
> 3. In SDK , we might try to unify all the Put traits somehow, I didn't think about details.
> 4. SDK should handle all the asset locks, etc., internally. I should just do Identity::create(amount) and it should do the job. We might give an option (builder pattern?) to specify additional params, but basic approach should be as above.
> 5. It means SDK MUST be integrated with some kind of wallet, to be able to sign and exec txs on both L1 and L2, so that the hello world example that creates an identity with some registered name and sends some funds takes just a few screens.
> 6. We should have much less features in Cargo.toml. Like max 5 per crate. Otherwise nobody will understand them and will simply use full.
> 7. We need separate versioning of Sdk and DPP (and whatever we see as "public API"), to let us notify on breaking changes.
> 8. Bindings to JS and other technologies. Not sure if it even makes sense (how big will be a JS SDK created with bindings be?)

**Comment by QuantumExplorer** [comment]
1 - We have different ways to interact with Platform, often it means Item.push or Item.fetch/fetchMany. However it's very hard to find these items as you can't guess what they are called when it isn't obvious.

2 - Query inside fetch is complicated. Autocomplete should handle it.

**Comment by pshenmic** [comment]
I haven't used RS SDK yet because it requires core connection, but I wanna share some thoughts what we would like to see in an SDK:

#### Proofs
Is a requirement for mainnet production products. In order to build a secure web frontend, we need a secure way to receive the documents from the Platform.

#### Create all possible transactions with your SDK:
* Register Identity
* Update Identity
* Identity Top Up
* Identity Credit Transfer
* Identity CreditWithdrawal
* Register Data Contract
* Update Data Contract
* DocumentsBatch (Create)
* DocumentsBatch (Replace)
* DocumentsBatch (Delete)
* DocumentsBatch (Transfer)
* DocumentsBatch (Update price)
* DocumentsBatch (Purchase)
* Masternode Vote

#### Pass signing to the external application (Mobile Dash Wallet, Electrum Dash,  WalletConnect, etc)
We would like to see a way to pass the serialized transaction for signing it, so you don't directly expose keys in the browser

#### Be able to receive and transfer Core transactions.
DASH from Core chain is used for a creation and topping up your Identity, and the withdrawals also being used on the L1 address, so we would like to be able to handle it from the same SDK

#### Special transactions (ProRegTx, AssetLocks, etc)
In some rare cases, a custom special transactions are needed, and we would like to be able to create them as well.

#### Do not resync chain data each page reload
Synced recent LLMQ headers is a requirement for proofs verification, but we don't want to bother user with syncing it each time. SDK should tolerate page reloads without dropping data

#### Sending DAPI queries without wallet for a new users.
When a new user facing our Dash Platform application, it does not have the account yet, but should be able to read the data on the DAPP (possibly without Proofs)

#### SDK Bundle size
Bundle size should be as small as possible, preferrable < 1-2 mb, so it does not take forever for a new leads (currently it weights 37.5 mb). It is also should be modular, allowing developers require functions independently. As an example, you could only decode the identity recieved from DAPI, so you don't need to download and import the whole SDK bundle.

#### Debugging mode (logs)
We need an option to raise logging level, so that developers could figure out whats hapenning wrong. I believe it is not working in browser yet because we have not found a way to do that. A use case for example, `account.getWallet()` is an async function and working in a blocking way, waiting until everything downloads , and there is not logging in the console by the default. In the Node, you can set LOG_LEVEL environment which does not work in browsers.

#### Better pagination in queries
Currently, it is not possible to see a total items in returning request, and in order to count all items in the data contract, you have to initiate N / 100 queries for getting to the final page. There is no integer supported in the pagination query option, it only accepts identifier, which you only within the page scope.

DApp applications I believe will be using getDocuments query a lot, and its necessary to have a rich querying, sorting and paging options. Certain things could be not supported on the protocol level, and we might need to do it on the frontend. As an example, get all NFTs for a user and calculate all balance, get history of the document transfers for user, etc.

#### Get Masternode Identity by public key hash
It is not possible to query information about the identity for a masternode identity, because it is not unique and stores in the different grovedb index. When user specify a key, we want to get information about his identity instantly. We workarounded that with asking user to input the identifier of his masternode and make an additional getIdentityByIdentifier call. It would be great to just search by public key hash (just like the regular Identities)

#### Validate transaction before sending RPC
It is not possible to catch all the errors on the client side, because `check_tx` RPC is only available in the Tenderdash, DAPI only allows you to broadcast it.

It is a necessary to check all of your transactions before sending, because some data contracts requires more than 1 transaction to send, and we have no way to check that. For example, registering an Identity happens by sending 2 transactions, preorder + document. There is many things that can go wrong on different level, it would be good to reduce amount of them from the frontend.

#### Estimate fee method 
We need a way to estimate a transaction before sending, just like many blockchain frontends do. Before you send a transaction you want to see exact amount that it would cost for you

#### Good documentation and a gRPC Playground
That's what I hear back from the devs who are using current Dash SDK, that it lack good and easy to read documentation and it takes a lot of time even for a simple transacations. No quickstart guides and stuff like that
