### ISSUE TITLE
bug(dashmate): cannot change base template settings before setup

### ISSUE THREAD

**Issue by pshenmic** [dashpay/platform#784]
## Expected Behavior

You can change base template config and it will persist during `setup` command

## Current Behavior

Some config values gets overwritten because migrations are getting executing during `setup` process

## Possible Solution

Fix this thing, so you can change some default values in the first place.

## Steps to Reproduce (for bugs)

1. dashmate config set --config local platform.drive.tenderdash.log.level trace
2. dashmate setup local

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop, server, or mobile):
* Link to your project:

**Comment by shumkov** [comment]
@pshenmic This is happening because the `dashmate setup local` command configures logs verbosity. The config options that the `dashmate setup local` doesn't touch are inherited from the local preset. If you still think it's a bug please reopen it and provide a description how you think it should behave.
