### ISSUE TITLE
Can't Store balance into a Wallet 

### ISSUE THREAD

**Issue by AhmedElwerdany** [dashpay/platform#790]
I am trying to add `dash` to a wallet, but I keep getting a message `Not enough balance (0) to cover burn amount of 1000000` 
## Expected Behavior
I Expect the address that I've added `dash` / `money` to it, to be able to create Identities. 

## Current Behavior
error `Not enough balance (0) to cover burn amount of 1000000` when trying to create Identity 

## Steps to Reproduce (for bugs)

1. 
```javascript
import { Client } from 'dash';

const clientOpts = {
  network: 'local',
  wallet: {
    mnemoic: null,
    // mnemoic: 'later van settle digital bone zone decrease year robust waste seat banner'
  },
};

const client = new Client(clientOpts);
```
2.
```javascript
  const account = await client.getWalletAccount();
  const mnemnoic = client.wallet.exportWallet();
  const address = account.getUnusedAddress() // abc
```
3.
`dashmate wallet:mint 10 --address=abc --config=local_seed`
4.
```javascript
const identity = client.platform.identities.register();
```
5.
error: `Not enough balance (0) to cover burn amount of 1000000`

## Your Environment

* Version used: `"@dashevo/dapi-client": "*",
    "@dashevo/dpp": "*", "dash": "^3.23.2",`
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop, server, or mobile): ( Windows 10 )
* Link to your project:

**Comment by pshenmic** [comment]
Hey there :) Glad to see you here

Seems like you just have a typo in your client configuration:
```
mnemoic: null,
```

The field for the seed phrase should be `mnemonic`. And since its undefined in your case, you just ending up having fresh, new keychain (and new pool of addresses) every run. So its working, you just minted up Dash for the addresses you don't have access for.

I double checked your commands, and with the correct field name and mnemonic, I was able to get money in my pocket.

**Comment by AhmedElwerdany** [comment]
that was really it 😅 . thank you !
